language: go

go:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - tip

sudo: false

install:
    - go get github.com/mattn/goveralls

script:
    - GOOS=darwin go build
    - GOOS=windows go build
    - GOOS=linux go build
    - $HOME/gopath/bin/goveralls -service=travis-ci
